services:

  backend:
    build: ./backend
    container_name: worddee-backend
    ports:
      - "8000:8000"
    networks:
      - worddee-network

  n8n:
    image: n8nio/n8n:latest
    container_name: worddee-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_ENCRYPTION_KEY=abcdef1234567890abcdef1234567890
      - N8N_COMMUNITY_PACKAGES_ENABLED=false
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - worddee-network

  frontend:
    build: ./frontend
    container_name: worddee-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - n8n
    networks:
      - worddee-network

networks:
  worddee-network:
